require('application/chart')
require('application/flash_messages')
require('application/upload')
require('application/persist_scroll')
require('application/tooltip')
require('application/button_inside_link')
require('application/auto_submit')
require('application/tagging')
