commons: &commons
  adapter: "mysql2"
  charset: "utf8mb4"
  collation: "utf8mb4_unicode_ci"

development:
  <<: *commons
  database: "employer-portal-dev"

test:
  <<: *commons
  database: "employer-portal-test"

production:
  <<: *commons
